provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage , 'dev'}
  mode: ${opt:mode , 'online'}
  region: 'eu-central-1'
  logRetentionInDays: 90

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - ./**

service:
  name: 'express_boilerplate'
  id: ${self:service.name}-${self:provider.stage}
  apiBasePath: '/express'
  graphQLBasePath: '/graphql'
  Route53HostedZoneId: xy

functions:
  express:
    handler: packages/express_lambda/dist/handler.handler
    timeout: 30
    events:
      - http: GET ${self:service.apiBasePath}
      - http: POST ${self:service.apiBasePath}
    package:
      include:
        - packages/express_lambda/dist/**
  graphql:
    handler: packages/graphql_lambda/dist/handler.handler
    timeout: 30
    events:
      - http: GET ${self:service.graphQLBasePath}
      - http: POST ${self:service.graphQLBasePath}
    package:
      include:
        - packages/graphql_lambda/dist/**
